ALTER TABLE `projects`
	ADD COLUMN `PROJECTDURATION` INT NULL DEFAULT NULL AFTER `PROJECTEND`;

ALTER TABLE `projectquotations`
	ADD COLUMN `TOTALCOST` DECIMAL(18,2) NULL DEFAULT NULL AFTER `FINALCOST`;

ALTER TABLE `projectquotations`
	ADD COLUMN `DURATION` INT(11) NULL DEFAULT NULL AFTER `INVENTORY`;




